---
title: "R Notebook"
output: html_notebook
---


```{r}
library(rjson)
library(blsAPI)
library(ggplot2)
```

```{r}
## Pull the data via the API
payload <- list(
  'seriesid'=c('LAUCN360610000000004', 'LAUCN360610000000006'),
  'startyear'=2015,
  'endyear'=2019)
response <- blsAPI(payload, 2)
json <- fromJSON(response)

```


```{r}
## Process results
apiDF <- function(data){
  df <- data.frame(year=character(),
                   period=character(),
                   periodName=character(),
                   value=character(),
                   stringsAsFactors=FALSE)
  
  i <- 0
  for(d in data){
    i <- i + 1
    df[i,] <- unlist(d)
  }
  return(df)
}

unemployed.df <- apiDF(json$Results$series[[1]]$data)
labor.force.df <- apiDF(json$Results$series[[2]]$data)
```



```{r}
## Change value type from character to numeric
unemployed.df[,4] <- as.numeric(unemployed.df[,4])
labor.force.df[,4] <- as.numeric(labor.force.df[,4])
```


```{r}
## Rename value prior to merging
names(unemployed.df)[4] <- 'unemployed'
names(labor.force.df)[4] <- 'labor.force'
```


```{r}
## Merge data frames
df <- merge(unemployed.df, labor.force.df)
df
```


```{r}
## Create date and unemployement rate
df$unemployment.rate <- df$unemployed / df$labor.force
df$date <- as.POSIXct(strptime(paste0('1',df$periodName,df$year), '%d%B%Y'))
```

```{r}
## Beginning and end dates for the Great Recession (used in shaded area)
gr.start <- as.POSIXct(strptime('1December2015', '%d%B%Y'))
gr.end <- as.POSIXct(strptime('1June2020', '%d%B%Y'))
```

```{r}
## Plot the data
ggplot(df) + geom_rect(aes(xmin = gr.start, xmax = gr.end, ymin = -Inf, ymax = Inf), alpha = 0.4, fill="#DDDDDD") + geom_line(aes(date, unemployment.rate*100)) + ylab('Percent of labor force')  + xlab('Great Recession shaded in gray') + ggtitle('Unemployment Rate for Manhattan, NY (Jan 2007 to Dec 2010)') + theme_bw()
```
```{r}
library(tidyverse)
```
```{r}
tmp <- tempfile()
write_csv(df, tmp)

write_csv(df, path = "df.csv")
```

